### ISSUE TITLE
РК1

### ISSUE THREAD

**Issue by IliaBulavintsev** [frontend-park-mail-ru/2017_1_Angry-Beavers#3]
- [x] Ваше приложение задеплоено на heroku
- [x] Страницы приложения переключаются без перезагрузки сайта
- [x] Выполнена интеграция с бекендом
- [x] Используется модульный и компонентный подход, используются шаблонизаторы
- [ ] Есть формы авторизации и регистрации с валидацией данных
- [x] Есть линтер, который не ругается на ваш код
- [x] Всё ваше API протестировано и тесты действительно проходят

**Comment by ostapenko-me** [comment]
## Замечания

- Либы не должны лежать в репозитории
- Доделать дзшки
