### ISSUE TITLE
РК2

### ISSUE THREAD

**Issue by IliaBulavintsev** [frontend-park-mail-ru/2017_1_Angry-Beavers#7]
- [ ] Всё ваше API протестировано и тесты действительно проходят]У вас есть синглплеер и в него можно поиграть!
- [ ] Ваш код написан с использованием ES6-модулей
- [ ] В ваших проектах есть правильно работающий роутинг, работают переходы по страницам и меняется адрес в адресной строке браузера
- [ ] Вы используете БЭМ

**Comment by IliaBulavintsev** [comment]
- [ ] Всю логику для работы с сессией переместить в модель user

**Comment by DmitryDorofeev** [comment]
- [ ] синглплеер

- [ ] бекендеры должны знать код
